config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :groups
  get 'home/index'
  resources :point_of_interests do
    get 'comments', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :users
end

app/models/point_of_interest.rb
class PointOfInterest < ApplicationRecord

  acts_as_commontable dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord

  acts_as_commontator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :lat, :lng)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pois = PointOfInterest.all
  end
end

app/controllers/point_of_interests_controller.rb
class PointOfInterestsController < ApplicationController
  before_action :set_point_of_interest, only: %i[ show edit update destroy comments]

  # GET /point_of_interests or /point_of_interests.json
  def index
    @point_of_interests = PointOfInterest.all
  end

  # GET /point_of_interests/1 or /point_of_interests/1.json
  def show
  end

  def comments
    @comments = @poi.commontator_thread.comments
    render partial: 'comments', locals: { poi: @poi }
  end

  # GET /point_of_interests/new
  def new
    @point_of_interest = PointOfInterest.new
  end

  # GET /point_of_interests/1/edit
  def edit
  end

  # POST /point_of_interests or /point_of_interests.json
  def create
    @point_of_interest = PointOfInterest.new(point_of_interest_params)

    respond_to do |format|
      if @point_of_interest.save
        format.html { redirect_to point_of_interest_url(@point_of_interest), notice: "Point of interest was successfully created." }
        format.json { render :show, status: :created, location: @point_of_interest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @point_of_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /point_of_interests/1 or /point_of_interests/1.json
  def update
    respond_to do |format|
      if @point_of_interest.update(point_of_interest_params)
        format.html { redirect_to point_of_interest_url(@point_of_interest), notice: "Point of interest was successfully updated." }
        format.json { render :show, status: :ok, location: @point_of_interest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @point_of_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_of_interests/1 or /point_of_interests/1.json
  def destroy
    @point_of_interest.destroy

    respond_to do |format|
      format.html { redirect_to point_of_interests_url, notice: "Point of interest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_of_interest
      @point_of_interest = PointOfInterest.find(params[:id])
      @poi = @point_of_interest
    end

    # Only allow a list of trusted parameters through.
    def point_of_interest_params
      params.require(:point_of_interest).permit(:title, :description, :latitude, :longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:display_name, :email, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/point_of_interests_helper.rb
module PointOfInterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.label :center_lat, style: "display: block" %>
    <%= form.text_field :center_lat %>
  </div>

  <div>
    <%= form.label :center_lng, style: "display: block" %>
    <%= form.text_field :center_lng %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

  <p>
    <strong>Center lat:</strong>
    <%= group.lat %>
  </p>

  <p>
    <strong>Center lng:</strong>
    <%= group.lng %>
  </p>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
    <p>
      <%= link_to "Show this group", group %>
    </p>
  <% end %>
</div>

<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/home/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-10'>
      <h1>Home#index</h1>
    </div>
    <div class='col-2'>
      <%= link_to 'New idea', new_point_of_interest_path %>
    </div>
  </div>


  <div class="row">
    <div class="col-6">
      <div id="map" style="height:600px;"></div>
    </div>

    <div class="col-6" id="comments-section">
    </div>
  </div>
</div>

<script>
     <%= render partial: 'shared/map' %>
     // Add markers to the map for each infrastructure idea
     <% @pois.each do |poi| %>
       var marker = L.marker([<%= poi.latitude %>, <%= poi.longitude %>]).addTo(map);

       marker.id = <%= poi.id %>

       $.ajax({
         url: '<%= comments_point_of_interest_path(poi) %>',
         type: 'GET',
         success: function(data) {
           $('#comments-section').html(data);
         },
        error: function(xhr, status, error) {
          console.log(error);
        }
      });

    <% end %>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geodiscuss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/point_of_interests/_comments.html.erb
Showing comments for idea <%= @poi.id %>
<%= commontator_thread(@poi) %>

app/views/point_of_interests/_form.html.erb
<%= form_with(model: point_of_interest) do |form| %>
  <% if point_of_interest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(point_of_interest.errors.count, "error") %> prohibited this point_of_interest from being saved:</h2>

      <ul>
        <% point_of_interest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div id="map" style="height:200px; width:200px"></div>

  <script>
     <%= render partial: 'shared/map' %>

	     var marker = L.marker();

         function onMapClick(e) {
            marker
                .setLatLng(e.latlng)
                .addTo(map);
			document.getElementById('point_of_interest_latitude').value = e.latlng.lat;
			document.getElementById('point_of_interest_longitude').value = e.latlng.lng;
         }

         map.on('click', onMapClick);

  </script>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/point_of_interests/_point_of_interest.html.erb
<div id="<%= dom_id point_of_interest %>">
  <p>
    <strong>Title:</strong>
    <%= point_of_interest.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= point_of_interest.description %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= point_of_interest.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= point_of_interest.longitude %>
  </p>

</div>

app/views/point_of_interests/edit.html.erb
<h1>Editing point of interest</h1>

<%= render "form", point_of_interest: @point_of_interest %>

<br>

<div>
  <%= link_to "Show this point of interest", @point_of_interest %> |
  <%= link_to "Back to point of interests", point_of_interests_path %>
</div>

app/views/point_of_interests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Point of interests</h1>

<div id="point_of_interests">
  <% @point_of_interests.each do |point_of_interest| %>
    <%= render point_of_interest %>
    <p>
      <%= link_to "Show this point of interest", point_of_interest %>
    </p>
  <% end %>
</div>

<%= link_to "New point of interest", new_point_of_interest_path %>

app/views/point_of_interests/new.html.erb
<h1>New point of interest</h1>

<%= render "form", point_of_interest: @point_of_interest %>

<br>

<div>
  <%= link_to "Back to point of interests", point_of_interests_path %>
</div>

app/views/point_of_interests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @point_of_interest %>

<div>
  <%= link_to "Edit this point of interest", edit_point_of_interest_path(@point_of_interest) %> |
  <%= link_to "Back to point of interests", point_of_interests_path %>

  <%= button_to "Destroy this point of interest", @point_of_interest, method: :delete %>
</div>

app/views/shared/_map.html.erb
     // Initialize the map
     <% map_lat = Group.first&.lat || 65.00821 %>
     <% map_lng = Group.first&.lng || 25.47082 %>
     var map = L.map('map').setView([<%= "#{map_lat}, #{map_lng}" %>], 13);

     // Add a tile layer to the map
     L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
       attribution: 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'
     }).addTo(map);

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :display_name, style: "display: block" %>
    <%= form.text_field :display_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Display name:</strong>
    <%= user.display_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>